name: Terraform Apply and Destroy
on:
  push:
    branches:
      - main

env: 
    AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
    AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
    TF_VAR_aws_key_pub: ${{secrets.TF_VAR_aws_key_pub}}

jobs: 
    terraform_plan:
        name: Workflow - Terraform Apply and Destroy (Automatically)
        runs-on: ubuntu-latest
        defaults:
            run:
                shell: bash
        steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Terraform Apply
          run: |
            terraform init
            terraform apply -auto-approve
            echo "the EC2 instance has been successfully applied!"
            sleep 10
            echo "destroying resources..."
            terraform destroy -auto-approve
            echo "the instance has been successfully destroyed!"
