name: Terraform Apply
on: workflow_dispatch

env: 
    AWS_ACCESS_KEY_ID: ${{secrets.GITHUB_TOKEN.AWS_ACCESS_KEY_ID}}
    AWS_SECRET_ACCESS_KEY: ${{secrets.GITHUB_TOKEN.AWS_SECRET_ACCESS_KEY}}
    TF_VAR_aws_key_pub: ${{secrets.GITHUB_TOKEN.TF_VAR_aws_key_pub}}

jobs: 
    terraform_plan:
        name: Workflow - Terraform Apply 
        runs-on: ubuntu-latest
        defaults:
            run:
                shell: bash
        steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Terraform Apply
          run: |
            terraform init
            terraform apply -auto-approve
